# Generated by Django 3.1.3 on 2020-11-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0002_patient_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name_plural': 'slides'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='slides',
        ),
        migrations.AddField(
            model_name='slide',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='labeller.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='pid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='sid',
            field=models.IntegerField(unique=True),
        ),
    ]
