# Generated by Django 3.1.3 on 2020-11-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0003_auto_20201110_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'patients'},
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField(unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='labeller.slide')),
            ],
            options={
                'verbose_name_plural': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('label', models.CharField(default='unlabelled', max_length=200)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='labeller.region')),
            ],
            options={
                'verbose_name_plural': 'cells',
            },
        ),
    ]
