# Generated by Django 3.1.3 on 2020-11-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0004_auto_20201110_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='image',
            field=models.ImageField(upload_to='static/regions/'),
        ),
    ]
