# Generated by Django 3.1.3 on 2020-11-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0005_auto_20201111_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='image',
            field=models.ImageField(upload_to='xyzd/'),
        ),
    ]
