# Generated by Django 3.1.3 on 2020-11-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0007_auto_20201111_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='image',
            field=models.ImageField(upload_to='rrr'),
        ),
    ]
