# Generated by Django 3.1.3 on 2020-11-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0008_auto_20201111_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='labelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cell',
            name='image',
            field=models.ImageField(upload_to='cells'),
        ),
        migrations.AlterField(
            model_name='region',
            name='image',
            field=models.ImageField(upload_to='regions'),
        ),
    ]
