# Generated by Django 3.1.3 on 2020-11-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0009_auto_20201112_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='label',
            field=models.CharField(choices=[('UL', 'unlabelled'), ('BL', 'blast'), ('M1', 'M1: myelocyte'), ('M2', 'M2: promyelocyte'), ('M3', 'M3: metamyelocyte'), ('N1', 'M4: band'), ('N2', 'M5: seg'), ('E1', 'E1: immature eosinophil'), ('E2', 'E2: eosinophil'), ('B1', 'B1: immature basophil'), ('B2', 'B2: basophil'), ('HG', 'hematogone'), ('L1', 'lymphoblast'), ('L2', 'mature lymphocyte'), ('LGL', 'LGL'), ('PC', 'plasma cell'), ('E1', 'E1: pronormoblast'), ('E2', 'E2: basophilic normoblsat'), ('E3', 'E3: polychrmoatic normoblast'), ('E4', 'E4: orthocrhomic normoblast (nucleated red)'), ('E5', 'E5: polychromatic erythrocyte (reticulocyte)'), ('E6', 'E6: mature erythrocyte'), ('M1', 'M1: monoblast equivalent'), ('M2', 'M2: mature monocyte'), ('H1', 'H1: histiocyte'), ('U1', 'Unknown intact cell'), ('ART', 'Artifact (crush or other)')], default='UL', max_length=4),
        ),
    ]
