# Generated by Django 3.1.3 on 2020-11-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0011_auto_20201112_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='cid',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
