# Generated by Django 3.1.3 on 2020-11-12 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0012_auto_20201112_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='image',
            field=models.ImageField(editable=False, upload_to='cells'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='region',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='labeller.region'),
        ),
    ]
