# Generated by Django 3.1.3 on 2020-11-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0014_auto_20201112_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'verbose_name_plural': models.BooleanField(default=False)},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': models.BooleanField(default=False)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': models.BooleanField(default=False)},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name_plural': models.BooleanField(default=False)},
        ),
        migrations.AddField(
            model_name='cell',
            name='OTHER',
            field=models.BooleanField(default=False),
        ),
    ]
