# Generated by Django 3.1.3 on 2020-11-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0020_auto_20201113_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'verbose_name_plural': models.BooleanField(default=False)},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': models.BooleanField(default=False)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': models.BooleanField(default=False)},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name_plural': models.BooleanField(default=False)},
        ),
    ]
