# Generated by Django 3.1.3 on 2020-11-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0022_auto_20201117_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'verbose_name_plural': 'Cells'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name_plural': 'Slides'},
        ),
    ]
