# Generated by Django 3.1.3 on 2020-11-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0024_auto_20201119_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='cell_type2',
            field=models.CharField(default='UL', max_length=50),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_type',
            field=models.CharField(choices=[('M1', 'blast (1)'), ('M2', 'myelocyte (2)'), ('M3', 'promyelocyte (3)'), ('M4', 'metamyelocyte (4)'), ('M5', 'band (5)'), ('M6', 'seg (6)'), ('E1', 'immature eo (q)'), ('E2', 'eo (w)'), ('B1', 'imm base (e)'), ('B2', 'baso (r)'), ('M1', 'monoblast (t)'), ('M2', 'monocyte'), ('L0', 'lymphoblast'), ('L1', 'hematogone'), ('L2', 'lymphocyte'), ('L3', 'lgl'), ('L4', 'plasma cell'), ('E1', 'pronormoblast'), ('E2', 'basophilic normoblast'), ('E3', 'polychromatic'), ('E4', 'orthochromic'), ('E5', 'retic'), ('E6', 'rbc'), ('U1', 'artifact'), ('U2', 'unknown'), ('U3', 'other'), ('U4', 'histiocyte'), ('UL', 'unlabelled')], default='UL', max_length=2),
        ),
    ]
