# Generated by Django 3.1.3 on 2020-11-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0025_auto_20201126_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='cell_type',
        ),
    ]
