# Generated by Django 3.1.3 on 2020-11-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0028_auto_20201128_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='cell_type',
            field=models.CharField(default='UL', max_length=50),
        ),
    ]
