# Generated by Django 3.1.3 on 2020-12-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0029_cell_cell_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='x',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='region',
            name='y',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='slide',
            name='dzi_path',
            field=models.CharField(default='', max_length=300),
        ),
    ]
