# Generated by Django 3.1.3 on 2020-12-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0030_auto_20201228_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='svs_path',
            field=models.FileField(default=' ', max_length=300, upload_to=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='dzi_path',
            field=models.FileField(max_length=300, upload_to=None),
        ),
    ]
