# Generated by Django 3.1.3 on 2021-01-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0033_auto_20210109_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='height',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='cell',
            name='width',
            field=models.FloatField(default=-1),
        ),
    ]
