# Generated by Django 3.1.3 on 2021-02-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0035_region_all_wc_located'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='all_wc_classified',
            field=models.BooleanField(default=False),
        ),
    ]
