# Generated by Django 3.1.3 on 2021-03-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0036_region_all_wc_classified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('regions', models.ManyToManyField(to='labeller.Region')),
            ],
        ),
    ]
