# Generated by Django 3.1.3 on 2021-03-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0037_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
    ]
