# Generated by Django 3.1.3 on 2021-03-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0038_remove_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
