# Generated by Django 3.1.3 on 2021-03-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0042_remove_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
