# Generated by Django 3.1.3 on 2021-05-14 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0044_cellclassification_newcell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CellClassification',
        ),
        migrations.DeleteModel(
            name='NewCell',
        ),
        migrations.RemoveField(
            model_name='project',
            name='regions',
        ),
        migrations.AddField(
            model_name='cell',
            name='center_x_slide',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='cell',
            name='center_y_slide',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='cell',
            name='center_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cell',
            name='center_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cell',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='labeller.region'),
        ),
    ]
