# Generated by Django 3.1.3 on 2021-10-17 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0049_auto_20211012_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='dzi_path',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='slides'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='labeller.patient'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='svs_path',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='slides'),
        ),
    ]
