# Generated by Django 3.1.3 on 2021-10-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0051_auto_20211026_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureName', models.CharField(blank=True, max_length=64, null=True)),
                ('featureAbbreviation', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='cellFeatures',
            field=models.ManyToManyField(to='labeller.CellFeature'),
        ),
    ]
