# Generated by Django 3.1.3 on 2021-12-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0059_auto_20211228_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='userNotes',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='cell',
            name='notes',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='celltype',
            name='notes',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
