# Generated by Django 3.1.3 on 2022-01-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0060_auto_20211230_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='slide',
            name='diagnosis',
            field=models.ManyToManyField(related_name='slides', to='labeller.Diagnosis'),
        ),
    ]
