# Generated by Django 3.1.3 on 2022-01-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0061_auto_20220104_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.AddField(
            model_name='cell',
            name='cell_types',
            field=models.ManyToManyField(related_name='cells', to='labeller.CellType'),
        ),
    ]
