# Generated by Django 3.1.3 on 2022-01-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0062_auto_20220110_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CellLabel',
        ),
    ]
