# Generated by Django 3.1.3 on 2022-01-11 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeller', '0063_delete_celllabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slides',
            field=models.ManyToManyField(related_name='slides_with_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='projects_with_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
