# Generated by Django 3.1.3 on 2022-01-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0064_auto_20220111_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slides',
            field=models.ManyToManyField(related_name='slides_with_project', to='labeller.Slide'),
        ),
    ]
