# Generated by Django 3.1.3 on 2022-01-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0065_auto_20220111_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='slide',
            name='diagnoses',
            field=models.ManyToManyField(related_name='slides_with_diagnosis', to='labeller.Diagnosis'),
        ),
    ]
