# Generated by Django 3.1.3 on 2022-04-07 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeller', '0066_auto_20220113_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labeller.region'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slides',
            field=models.ManyToManyField(related_name='project_with_slides', to='labeller.Slide'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='diagnoses',
            field=models.ManyToManyField(blank=True, related_name='slides_with_diagnosis', to='labeller.Diagnosis'),
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isBlind', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Collaborators',
            },
        ),
        migrations.AddField(
            model_name='slide',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='slides_with_collaborators', to='labeller.Collaborator'),
        ),
    ]
